export const LOAD_APP_DATA = 'load_app_data'
// export const CREATE_FORM = 'create_form'
export const SAMPLE_DATA_OVERWRITE = 'sample_data_overwrite'
export const SAMPLE_DATA_APPEND = 'sample_data_append'
export const SAMPLE_DATA_DELETE = 'sample_data_delete'

export const CHECK_AUTH_STATUS = 'check_auth_status'
export const LOGIN = 'login'
export const LOGIN_SUCCESS = 'login_success'
export const LOGIN_FAIL = 'login_fail'
export const LOGOUT = 'logout'

export const LOGIN_FIELD_UPDATE = 'login_field_update'
export const SEARCH_FIELD_UPDATE = 'search_field_update'
export const SEARCH_QUERY = 'search_query'

export const FORM_SAVE = 'form_save'
export const FORM_UPDATE = 'form_update'
export const FORM_SAVE_COMPLETE = 'form_save_complete'
export const FORM_FIELD_UPDATE = 'form_field_update'
export const FORM_ERROR = 'form_error'
export const CARD_DELETE = 'card_delete'
export const CARD_EDIT = 'card_edit'
export const CARDS_DELETE_ALL = 'cards_delete_all'

export const LIST_SAVE = 'list_save'
export const LIST_CLEAR = 'list_clear'
export const LIST_PRINT = 'list_print'

export * from './appActions'
export * from './authActions'
export * from './itemActions'